- asdf:
  - plugin: yarn
    url: https://github.com/twuni/asdf-yarn.git
    global: 1.22.4
    versions:
      - 1.22.4
  - plugin: ruby
    url: https://github.com/asdf-vm/asdf-ruby.git
    global: 2.6.5
    versions:
      - 2.6.5
  - plugin: nodejs
    url: https://github.com/asdf-vm/asdf-nodejs.git 
    global: 14.4.0
    versions:
      - 14.4.0
      - 12.16.0
      - 10.16.3
  - plugin: erlang
    url: https://github.com/asdf-vm/asdf-erlang.git
    global: 23.0.2
    versions:
      - 23.0.2
  - plugin: elixir
    url: https://github.com/asdf-vm/asdf-elixir.git
    global: 1.10.4
    versions:
      - 1.10.4
  - plugin: smlnj 
    url: https://github.com/samontea/asdf-smlnj.git
    global: 110.97
    versions:
      - 110.97
  - plugin: deno
    url: https://github.com/asdf-community/asdf-deno.git
    global: 1.1.3
    versions:
      - 1.1.3
