- link:
    ~/.config/asdf/.asdfrc: tools/asdf/.asdfrc
- asdf:
  - plugin: yarn
    url: https://github.com/twuni/asdf-yarn.git
    global: 1.22.10
    versions:
      - 1.22.10
  - plugin: ruby
    url: https://github.com/asdf-vm/asdf-ruby.git
    global: 2.6.5
    versions:
      - 2.6.5
      - 2.6.6
      - 2.7.1
  - plugin: nodejs
    url: https://github.com/asdf-vm/asdf-nodejs.git 
    global: 16.1.0
    versions:
      - 16.1.0
      - 14.5.0
  - plugin: erlang
    url: https://github.com/asdf-vm/asdf-erlang.git
    global: 23.0.2
    versions:
      - 23.0.2
  - plugin: elixir
    url: https://github.com/asdf-vm/asdf-elixir.git
    global: 1.10.4
    versions:
      - 1.10.4
  - plugin: smlnj 
    url: https://github.com/samontea/asdf-smlnj.git
    global: 110.97
    versions:
      - 110.97
  - plugin: deno
    url: https://github.com/asdf-community/asdf-deno.git
    global: 1.10.2
    versions:
      - 1.10.2
  - plugin: rust
    url: https://github.com/code-lever/asdf-rust.git
    global: 1.45.2 
    versions:
      - 1.45.2
  - plugin: flutter
    url: https://github.com/oae/asdf-flutter.git 
    global: 2.0.4-stable
    versions:
      - 2.0.4-stable
